/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/oscar/git/rover/catkin_ws/src/odometry/srv/DisplacementMiddleWheels.srv
 *
 */


#ifndef ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSRESPONSE_H
#define ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace odometry
{
template <class ContainerAllocator>
struct DisplacementMiddleWheelsResponse_
{
  typedef DisplacementMiddleWheelsResponse_<ContainerAllocator> Type;

  DisplacementMiddleWheelsResponse_()
    : diffPosition()  {
    }
  DisplacementMiddleWheelsResponse_(const ContainerAllocator& _alloc)
    : diffPosition(_alloc)  {
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _diffPosition_type;
  _diffPosition_type diffPosition;




  typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DisplacementMiddleWheelsResponse_

typedef ::odometry::DisplacementMiddleWheelsResponse_<std::allocator<void> > DisplacementMiddleWheelsResponse;

typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsResponse > DisplacementMiddleWheelsResponsePtr;
typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsResponse const> DisplacementMiddleWheelsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometry

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'odometry': ['/home/oscar/git/rover/catkin_ws/src/odometry/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1646ae4c7982d9ce10c990c5c93a18b6";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1646ae4c7982d9ceULL;
  static const uint64_t static_value2 = 0x10c990c5c93a18b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometry/DisplacementMiddleWheelsResponse";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose diffPosition\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diffPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DisplacementMiddleWheelsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometry::DisplacementMiddleWheelsResponse_<ContainerAllocator>& v)
  {
    s << indent << "diffPosition: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.diffPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSRESPONSE_H
