/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/oscar/git/rover/catkin_ws/src/odometry/srv/DisplacementMiddleWheels.srv
 *
 */


#ifndef ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELS_H
#define ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELS_H

#include <ros/service_traits.h>


#include <odometry/DisplacementMiddleWheelsRequest.h>
#include <odometry/DisplacementMiddleWheelsResponse.h>


namespace odometry
{

struct DisplacementMiddleWheels
{

typedef DisplacementMiddleWheelsRequest Request;
typedef DisplacementMiddleWheelsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DisplacementMiddleWheels
} // namespace odometry


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::odometry::DisplacementMiddleWheels > {
  static const char* value()
  {
    return "298fb6689bea16a3681240b79db77220";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheels&) { return value(); }
};

template<>
struct DataType< ::odometry::DisplacementMiddleWheels > {
  static const char* value()
  {
    return "odometry/DisplacementMiddleWheels";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheels&) { return value(); }
};


// service_traits::MD5Sum< ::odometry::DisplacementMiddleWheelsRequest> should match 
// service_traits::MD5Sum< ::odometry::DisplacementMiddleWheels > 
template<>
struct MD5Sum< ::odometry::DisplacementMiddleWheelsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::odometry::DisplacementMiddleWheels >::value();
  }
  static const char* value(const ::odometry::DisplacementMiddleWheelsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::odometry::DisplacementMiddleWheelsRequest> should match 
// service_traits::DataType< ::odometry::DisplacementMiddleWheels > 
template<>
struct DataType< ::odometry::DisplacementMiddleWheelsRequest>
{
  static const char* value()
  {
    return DataType< ::odometry::DisplacementMiddleWheels >::value();
  }
  static const char* value(const ::odometry::DisplacementMiddleWheelsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::odometry::DisplacementMiddleWheelsResponse> should match 
// service_traits::MD5Sum< ::odometry::DisplacementMiddleWheels > 
template<>
struct MD5Sum< ::odometry::DisplacementMiddleWheelsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::odometry::DisplacementMiddleWheels >::value();
  }
  static const char* value(const ::odometry::DisplacementMiddleWheelsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::odometry::DisplacementMiddleWheelsResponse> should match 
// service_traits::DataType< ::odometry::DisplacementMiddleWheels > 
template<>
struct DataType< ::odometry::DisplacementMiddleWheelsResponse>
{
  static const char* value()
  {
    return DataType< ::odometry::DisplacementMiddleWheels >::value();
  }
  static const char* value(const ::odometry::DisplacementMiddleWheelsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELS_H
