/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/oscar/git/rover/catkin_ws/src/odometry/srv/DisplacementMiddleWheels.srv
 *
 */


#ifndef ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSREQUEST_H
#define ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odometry
{
template <class ContainerAllocator>
struct DisplacementMiddleWheelsRequest_
{
  typedef DisplacementMiddleWheelsRequest_<ContainerAllocator> Type;

  DisplacementMiddleWheelsRequest_()
    : diffTachoLeft(0.0)
    , diffTachoRight(0.0)  {
    }
  DisplacementMiddleWheelsRequest_(const ContainerAllocator& _alloc)
    : diffTachoLeft(0.0)
    , diffTachoRight(0.0)  {
    }



   typedef float _diffTachoLeft_type;
  _diffTachoLeft_type diffTachoLeft;

   typedef float _diffTachoRight_type;
  _diffTachoRight_type diffTachoRight;




  typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DisplacementMiddleWheelsRequest_

typedef ::odometry::DisplacementMiddleWheelsRequest_<std::allocator<void> > DisplacementMiddleWheelsRequest;

typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsRequest > DisplacementMiddleWheelsRequestPtr;
typedef boost::shared_ptr< ::odometry::DisplacementMiddleWheelsRequest const> DisplacementMiddleWheelsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometry

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'odometry': ['/home/oscar/git/rover/catkin_ws/src/odometry/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f10eadf03d4db378f1b58a2e9b83c30";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f10eadf03d4db37ULL;
  static const uint64_t static_value2 = 0x8f1b58a2e9b83c30ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometry/DisplacementMiddleWheelsRequest";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 diffTachoLeft\n\
float32 diffTachoRight\n\
";
  }

  static const char* value(const ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.diffTachoLeft);
      stream.next(m.diffTachoRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DisplacementMiddleWheelsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometry::DisplacementMiddleWheelsRequest_<ContainerAllocator>& v)
  {
    s << indent << "diffTachoLeft: ";
    Printer<float>::stream(s, indent + "  ", v.diffTachoLeft);
    s << indent << "diffTachoRight: ";
    Printer<float>::stream(s, indent + "  ", v.diffTachoRight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_DISPLACEMENTMIDDLEWHEELSREQUEST_H
