/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/oscar/git/rover/catkin_ws/src/odometry/msg/Tachometers.msg
 *
 */


#ifndef ODOMETRY_MESSAGE_TACHOMETERS_H
#define ODOMETRY_MESSAGE_TACHOMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace odometry
{
template <class ContainerAllocator>
struct Tachometers_
{
  typedef Tachometers_<ContainerAllocator> Type;

  Tachometers_()
    : tachoFL(0)
    , tachoML(0)
    , tachoBL(0)
    , tachoFR(0)
    , tachoMR(0)
    , tachoBR(0)  {
    }
  Tachometers_(const ContainerAllocator& _alloc)
    : tachoFL(0)
    , tachoML(0)
    , tachoBL(0)
    , tachoFR(0)
    , tachoMR(0)
    , tachoBR(0)  {
    }



   typedef int32_t _tachoFL_type;
  _tachoFL_type tachoFL;

   typedef int32_t _tachoML_type;
  _tachoML_type tachoML;

   typedef int32_t _tachoBL_type;
  _tachoBL_type tachoBL;

   typedef int32_t _tachoFR_type;
  _tachoFR_type tachoFR;

   typedef int32_t _tachoMR_type;
  _tachoMR_type tachoMR;

   typedef int32_t _tachoBR_type;
  _tachoBR_type tachoBR;




  typedef boost::shared_ptr< ::odometry::Tachometers_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::odometry::Tachometers_<ContainerAllocator> const> ConstPtr;

}; // struct Tachometers_

typedef ::odometry::Tachometers_<std::allocator<void> > Tachometers;

typedef boost::shared_ptr< ::odometry::Tachometers > TachometersPtr;
typedef boost::shared_ptr< ::odometry::Tachometers const> TachometersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::odometry::Tachometers_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::odometry::Tachometers_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace odometry

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'odometry': ['/home/oscar/git/rover/catkin_ws/src/odometry/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::odometry::Tachometers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::odometry::Tachometers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::Tachometers_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::odometry::Tachometers_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::Tachometers_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::odometry::Tachometers_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::odometry::Tachometers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb233116002aa847d65f9b3f6ce21653";
  }

  static const char* value(const ::odometry::Tachometers_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb233116002aa847ULL;
  static const uint64_t static_value2 = 0xd65f9b3f6ce21653ULL;
};

template<class ContainerAllocator>
struct DataType< ::odometry::Tachometers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "odometry/Tachometers";
  }

  static const char* value(const ::odometry::Tachometers_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::odometry::Tachometers_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tachoFL\n\
int32 tachoML\n\
int32 tachoBL\n\
int32 tachoFR\n\
int32 tachoMR\n\
int32 tachoBR\n\
";
  }

  static const char* value(const ::odometry::Tachometers_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::odometry::Tachometers_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tachoFL);
      stream.next(m.tachoML);
      stream.next(m.tachoBL);
      stream.next(m.tachoFR);
      stream.next(m.tachoMR);
      stream.next(m.tachoBR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Tachometers_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::odometry::Tachometers_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::odometry::Tachometers_<ContainerAllocator>& v)
  {
    s << indent << "tachoFL: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoFL);
    s << indent << "tachoML: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoML);
    s << indent << "tachoBL: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoBL);
    s << indent << "tachoFR: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoFR);
    s << indent << "tachoMR: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoMR);
    s << indent << "tachoBR: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tachoBR);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ODOMETRY_MESSAGE_TACHOMETERS_H
