camera/wide_angle       : "/wide_angle/image_mono/compressed"
camera/wide_angle_hires : "/wide_angle/image_raw"
camera/arm              : "/camera_arm/image_color/compressed"
camera/arm_hires        : "/camera_arm/image_raw"
camera/pan_tilt         : "/econ"
camera/pan_tilt_hires   : "/econ/image_raw"
