camera/topic_haz_front  : "/hazcam_front/camera/image_raw"
camera/topic_haz_left   : "/hazcam_left/camera/image_raw"
camera/topic_haz_right  : "/hazcam_right/camera/image_raw"
camera/topic_haz_back   : "/hazcam_back/camera/image_raw"
camera/topic_arm        : "/camera_arm/camera/image_raw"
camera/topic_pan_tilt   : "/camera_pan_tilt/camera/image_raw"
