joystick/drive_mode :           "4"
joystick/arm_base_mode :        "8"
joystick/end_effector_mode :    "9"
joystick/camera_mode :          "5"
joystick/point_steer :          "3"
joystick/ackreman :             "2"
joystick/ackreman_moving :      "1" # motor enable
joystick/translatory :          "10"
joystick/coord_system :         "11"
#joystick/camera/arm :           "6"
#joystick/camera/pantilt :       "5"
#joystick/camera/haz_front :     "hat_top"
#joystick/camera/haz_back :      "hat_down"
