joystick/drive_mode :           "7"
joystick/arm_base_mode :        "8"
joystick/end_effector_mode :    "9"
joystick/camera_mode :          "10"
joystick/point_steer :          "3"
joystick/ackreman :             "2"
joystick/ackreman_moving :      "12"
joystick/claw_stop :          	"4"
joystick/coord_system :         "11"
joystick/camera/haz_front :     "hat_top"
joystick/camera/haz_back :      "hat_down"
/joystick/changeArmMotor:       "1"
joystick/close_claw: 			"5"
joystick/open_claw: 			"6"
