/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/oscar/git/rover/catkin_ws/src/control_systems/msg/MotionType.msg
 *
 */


#ifndef CONTROL_SYSTEMS_MESSAGE_MOTIONTYPE_H
#define CONTROL_SYSTEMS_MESSAGE_MOTIONTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_systems
{
template <class ContainerAllocator>
struct MotionType_
{
  typedef MotionType_<ContainerAllocator> Type;

  MotionType_()
    : ACKERMANN(0)
    , POINT(0)
    , TRANSLATORY(0)
    , SWERVE(0)  {
    }
  MotionType_(const ContainerAllocator& _alloc)
    : ACKERMANN(0)
    , POINT(0)
    , TRANSLATORY(0)
    , SWERVE(0)  {
    }



   typedef int8_t _ACKERMANN_type;
  _ACKERMANN_type ACKERMANN;

   typedef int8_t _POINT_type;
  _POINT_type POINT;

   typedef int8_t _TRANSLATORY_type;
  _TRANSLATORY_type TRANSLATORY;

   typedef int8_t _SWERVE_type;
  _SWERVE_type SWERVE;




  typedef boost::shared_ptr< ::control_systems::MotionType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_systems::MotionType_<ContainerAllocator> const> ConstPtr;

}; // struct MotionType_

typedef ::control_systems::MotionType_<std::allocator<void> > MotionType;

typedef boost::shared_ptr< ::control_systems::MotionType > MotionTypePtr;
typedef boost::shared_ptr< ::control_systems::MotionType const> MotionTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_systems::MotionType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_systems::MotionType_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_systems

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'control_systems': ['/home/oscar/git/rover/catkin_ws/src/control_systems/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_systems::MotionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_systems::MotionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_systems::MotionType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_systems::MotionType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_systems::MotionType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_systems::MotionType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_systems::MotionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00aa9f900bb945bea6467931de7f6956";
  }

  static const char* value(const ::control_systems::MotionType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00aa9f900bb945beULL;
  static const uint64_t static_value2 = 0xa6467931de7f6956ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_systems::MotionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_systems/MotionType";
  }

  static const char* value(const ::control_systems::MotionType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_systems::MotionType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 ACKERMANN\n\
int8 POINT\n\
int8 TRANSLATORY\n\
int8 SWERVE\n\
";
  }

  static const char* value(const ::control_systems::MotionType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_systems::MotionType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ACKERMANN);
      stream.next(m.POINT);
      stream.next(m.TRANSLATORY);
      stream.next(m.SWERVE);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotionType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_systems::MotionType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_systems::MotionType_<ContainerAllocator>& v)
  {
    s << indent << "ACKERMANN: ";
    Printer<int8_t>::stream(s, indent + "  ", v.ACKERMANN);
    s << indent << "POINT: ";
    Printer<int8_t>::stream(s, indent + "  ", v.POINT);
    s << indent << "TRANSLATORY: ";
    Printer<int8_t>::stream(s, indent + "  ", v.TRANSLATORY);
    s << indent << "SWERVE: ";
    Printer<int8_t>::stream(s, indent + "  ", v.SWERVE);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_SYSTEMS_MESSAGE_MOTIONTYPE_H
