/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/oscar/git/rover/catkin_ws/src/control_systems/msg/PanTiltZoom.msg
 *
 */


#ifndef CONTROL_SYSTEMS_MESSAGE_PANTILTZOOM_H
#define CONTROL_SYSTEMS_MESSAGE_PANTILTZOOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_systems
{
template <class ContainerAllocator>
struct PanTiltZoom_
{
  typedef PanTiltZoom_<ContainerAllocator> Type;

  PanTiltZoom_()
    : pan(0.0)
    , tilt(0.0)
    , zoom(0.0)  {
    }
  PanTiltZoom_(const ContainerAllocator& _alloc)
    : pan(0.0)
    , tilt(0.0)
    , zoom(0.0)  {
    }



   typedef float _pan_type;
  _pan_type pan;

   typedef float _tilt_type;
  _tilt_type tilt;

   typedef float _zoom_type;
  _zoom_type zoom;




  typedef boost::shared_ptr< ::control_systems::PanTiltZoom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_systems::PanTiltZoom_<ContainerAllocator> const> ConstPtr;

}; // struct PanTiltZoom_

typedef ::control_systems::PanTiltZoom_<std::allocator<void> > PanTiltZoom;

typedef boost::shared_ptr< ::control_systems::PanTiltZoom > PanTiltZoomPtr;
typedef boost::shared_ptr< ::control_systems::PanTiltZoom const> PanTiltZoomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_systems::PanTiltZoom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_systems::PanTiltZoom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_systems

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'control_systems': ['/home/oscar/git/rover/catkin_ws/src/control_systems/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_systems::PanTiltZoom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_systems::PanTiltZoom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_systems::PanTiltZoom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_systems::PanTiltZoom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_systems::PanTiltZoom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_systems::PanTiltZoom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_systems::PanTiltZoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eef4827ef5b8ba89a8c9fa0810a30294";
  }

  static const char* value(const ::control_systems::PanTiltZoom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeef4827ef5b8ba89ULL;
  static const uint64_t static_value2 = 0xa8c9fa0810a30294ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_systems::PanTiltZoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_systems/PanTiltZoom";
  }

  static const char* value(const ::control_systems::PanTiltZoom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_systems::PanTiltZoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 pan\n\
float32 tilt\n\
float32 zoom\n\
";
  }

  static const char* value(const ::control_systems::PanTiltZoom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_systems::PanTiltZoom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pan);
      stream.next(m.tilt);
      stream.next(m.zoom);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PanTiltZoom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_systems::PanTiltZoom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_systems::PanTiltZoom_<ContainerAllocator>& v)
  {
    s << indent << "pan: ";
    Printer<float>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<float>::stream(s, indent + "  ", v.tilt);
    s << indent << "zoom: ";
    Printer<float>::stream(s, indent + "  ", v.zoom);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_SYSTEMS_MESSAGE_PANTILTZOOM_H
