(cl:defpackage odometry-srv
  (:use )
  (:export
   "DISPLACEMENTMIDDLEWHEELS"
   "<DISPLACEMENTMIDDLEWHEELS-REQUEST>"
   "DISPLACEMENTMIDDLEWHEELS-REQUEST"
   "<DISPLACEMENTMIDDLEWHEELS-RESPONSE>"
   "DISPLACEMENTMIDDLEWHEELS-RESPONSE"
  ))

