# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created: Wed Feb 25 17:54:02 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(796, 840)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_49 = QtGui.QVBoxLayout()
        self.verticalLayout_49.setObjectName(_fromUtf8("verticalLayout_49"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.AG_SETPT = QtGui.QSpinBox(self.centralwidget)
        self.AG_SETPT.setMaximum(15)
        self.AG_SETPT.setObjectName(_fromUtf8("AG_SETPT"))
        self.verticalLayout.addWidget(self.AG_SETPT)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_45 = QtGui.QVBoxLayout()
        self.verticalLayout_45.setObjectName(_fromUtf8("verticalLayout_45"))
        self.label_45 = QtGui.QLabel(self.centralwidget)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_45.addWidget(self.label_45)
        self.ENPOL = QtGui.QSpinBox(self.centralwidget)
        self.ENPOL.setMaximum(1)
        self.ENPOL.setObjectName(_fromUtf8("ENPOL"))
        self.verticalLayout_45.addWidget(self.ENPOL)
        self.horizontalLayout.addLayout(self.verticalLayout_45)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.DIRPOL = QtGui.QSpinBox(self.centralwidget)
        self.DIRPOL.setMaximum(1)
        self.DIRPOL.setObjectName(_fromUtf8("DIRPOL"))
        self.verticalLayout_4.addWidget(self.DIRPOL)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_43 = QtGui.QVBoxLayout()
        self.verticalLayout_43.setObjectName(_fromUtf8("verticalLayout_43"))
        self.label_43 = QtGui.QLabel(self.centralwidget)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_43.addWidget(self.label_43)
        self.BRKPOL = QtGui.QSpinBox(self.centralwidget)
        self.BRKPOL.setMaximum(1)
        self.BRKPOL.setObjectName(_fromUtf8("BRKPOL"))
        self.verticalLayout_43.addWidget(self.BRKPOL)
        self.horizontalLayout.addLayout(self.verticalLayout_43)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_8.addWidget(self.label_8)
        self.SYNRECT = QtGui.QSpinBox(self.centralwidget)
        self.SYNRECT.setMaximum(1)
        self.SYNRECT.setObjectName(_fromUtf8("SYNRECT"))
        self.verticalLayout_8.addWidget(self.SYNRECT)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_32 = QtGui.QVBoxLayout()
        self.verticalLayout_32.setObjectName(_fromUtf8("verticalLayout_32"))
        self.label_32 = QtGui.QLabel(self.centralwidget)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_32.addWidget(self.label_32)
        self.PWMF = QtGui.QSpinBox(self.centralwidget)
        self.PWMF.setMaximum(3)
        self.PWMF.setObjectName(_fromUtf8("PWMF"))
        self.verticalLayout_32.addWidget(self.PWMF)
        self.horizontalLayout.addLayout(self.verticalLayout_32)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.SPDMODE = QtGui.QSpinBox(self.centralwidget)
        self.SPDMODE.setMaximum(3)
        self.SPDMODE.setObjectName(_fromUtf8("SPDMODE"))
        self.verticalLayout_2.addWidget(self.SPDMODE)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.FGSEL = QtGui.QSpinBox(self.centralwidget)
        self.FGSEL.setMaximum(3)
        self.FGSEL.setObjectName(_fromUtf8("FGSEL"))
        self.verticalLayout_3.addWidget(self.FGSEL)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_21.addWidget(self.label_21)
        self.BRKMOD = QtGui.QSpinBox(self.centralwidget)
        self.BRKMOD.setMaximum(1)
        self.BRKMOD.setObjectName(_fromUtf8("BRKMOD"))
        self.verticalLayout_21.addWidget(self.BRKMOD)
        self.horizontalLayout.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_22 = QtGui.QLabel(self.centralwidget)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_22.addWidget(self.label_22)
        self.RETRY = QtGui.QSpinBox(self.centralwidget)
        self.RETRY.setObjectName(_fromUtf8("RETRY"))
        self.verticalLayout_22.addWidget(self.RETRY)
        self.horizontalLayout.addLayout(self.verticalLayout_22)
        self.verticalLayout_49.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_48 = QtGui.QVBoxLayout()
        self.verticalLayout_48.setObjectName(_fromUtf8("verticalLayout_48"))
        self.label_48 = QtGui.QLabel(self.centralwidget)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.verticalLayout_48.addWidget(self.label_48)
        self.SPDREVS = QtGui.QSpinBox(self.centralwidget)
        self.SPDREVS.setMaximum(256)
        self.SPDREVS.setObjectName(_fromUtf8("SPDREVS"))
        self.verticalLayout_48.addWidget(self.SPDREVS)
        self.horizontalLayout_4.addLayout(self.verticalLayout_48)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_23 = QtGui.QLabel(self.centralwidget)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_23.addWidget(self.label_23)
        self.MINSPD = QtGui.QSpinBox(self.centralwidget)
        self.MINSPD.setMaximum(256)
        self.MINSPD.setObjectName(_fromUtf8("MINSPD"))
        self.verticalLayout_23.addWidget(self.MINSPD)
        self.horizontalLayout_4.addLayout(self.verticalLayout_23)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 2, 1, 1)
        self.speedSlider = QtGui.QSlider(self.centralwidget)
        self.speedSlider.setMaximum(100)
        self.speedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSlider.setObjectName(_fromUtf8("speedSlider"))
        self.gridLayout_3.addWidget(self.speedSlider, 1, 2, 1, 1)
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.label_33 = QtGui.QLabel(self.centralwidget)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_33.addWidget(self.label_33)
        self.ADVANCE = QtGui.QSpinBox(self.centralwidget)
        self.ADVANCE.setMaximum(256)
        self.ADVANCE.setObjectName(_fromUtf8("ADVANCE"))
        self.verticalLayout_33.addWidget(self.ADVANCE)
        self.gridLayout_3.addLayout(self.verticalLayout_33, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_34 = QtGui.QVBoxLayout()
        self.verticalLayout_34.setObjectName(_fromUtf8("verticalLayout_34"))
        self.label_34 = QtGui.QLabel(self.centralwidget)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_34.addWidget(self.label_34)
        self.BASIC = QtGui.QSpinBox(self.centralwidget)
        self.BASIC.setMaximum(1)
        self.BASIC.setObjectName(_fromUtf8("BASIC"))
        self.verticalLayout_34.addWidget(self.BASIC)
        self.horizontalLayout_3.addLayout(self.verticalLayout_34)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.label_25 = QtGui.QLabel(self.centralwidget)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_25.addWidget(self.label_25)
        self.SPEDTH = QtGui.QSpinBox(self.centralwidget)
        self.SPEDTH.setMaximum(7)
        self.SPEDTH.setObjectName(_fromUtf8("SPEDTH"))
        self.verticalLayout_25.addWidget(self.SPEDTH)
        self.horizontalLayout_3.addLayout(self.verticalLayout_25)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.label_24 = QtGui.QLabel(self.centralwidget)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_24.addWidget(self.label_24)
        self.MOD120 = QtGui.QSpinBox(self.centralwidget)
        self.MOD120.setMaximum(4096)
        self.MOD120.setObjectName(_fromUtf8("MOD120"))
        self.verticalLayout_24.addWidget(self.MOD120)
        self.horizontalLayout_3.addLayout(self.verticalLayout_24)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.speedValue = QtGui.QSpinBox(self.centralwidget)
        self.speedValue.setMinimumSize(QtCore.QSize(100, 0))
        self.speedValue.setObjectName(_fromUtf8("speedValue"))
        self.gridLayout_3.addWidget(self.speedValue, 1, 3, 1, 1)
        self.verticalLayout_49.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_47 = QtGui.QVBoxLayout()
        self.verticalLayout_47.setObjectName(_fromUtf8("verticalLayout_47"))
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.verticalLayout_47.addWidget(self.label_47)
        self.LRTIME = QtGui.QSpinBox(self.centralwidget)
        self.LRTIME.setMaximum(3)
        self.LRTIME.setObjectName(_fromUtf8("LRTIME"))
        self.verticalLayout_47.addWidget(self.LRTIME)
        self.horizontalLayout_2.addLayout(self.verticalLayout_47)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.HALLRST = QtGui.QSpinBox(self.centralwidget)
        self.HALLRST.setMaximum(3)
        self.HALLRST.setObjectName(_fromUtf8("HALLRST"))
        self.verticalLayout_5.addWidget(self.HALLRST)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_11.addWidget(self.label_11)
        self.DELAY = QtGui.QSpinBox(self.centralwidget)
        self.DELAY.setMaximum(1)
        self.DELAY.setObjectName(_fromUtf8("DELAY"))
        self.verticalLayout_11.addWidget(self.DELAY)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.label_26 = QtGui.QLabel(self.centralwidget)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_26.addWidget(self.label_26)
        self.AUTOADV = QtGui.QSpinBox(self.centralwidget)
        self.AUTOADV.setMaximum(1)
        self.AUTOADV.setObjectName(_fromUtf8("AUTOADV"))
        self.verticalLayout_26.addWidget(self.AUTOADV)
        self.horizontalLayout_2.addLayout(self.verticalLayout_26)
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName(_fromUtf8("verticalLayout_35"))
        self.label_35 = QtGui.QLabel(self.centralwidget)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_35.addWidget(self.label_35)
        self.AUTOGAIN = QtGui.QSpinBox(self.centralwidget)
        self.AUTOGAIN.setMaximum(1)
        self.AUTOGAIN.setObjectName(_fromUtf8("AUTOGAIN"))
        self.verticalLayout_35.addWidget(self.AUTOGAIN)
        self.horizontalLayout_2.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtGui.QVBoxLayout()
        self.verticalLayout_36.setObjectName(_fromUtf8("verticalLayout_36"))
        self.label_36 = QtGui.QLabel(self.centralwidget)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_36.addWidget(self.label_36)
        self.ENSINE = QtGui.QSpinBox(self.centralwidget)
        self.ENSINE.setMaximum(1)
        self.ENSINE.setObjectName(_fromUtf8("ENSINE"))
        self.verticalLayout_36.addWidget(self.ENSINE)
        self.horizontalLayout_2.addLayout(self.verticalLayout_36)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_27.addWidget(self.label_27)
        self.TDRIVE = QtGui.QSpinBox(self.centralwidget)
        self.TDRIVE.setMaximum(3)
        self.TDRIVE.setObjectName(_fromUtf8("TDRIVE"))
        self.verticalLayout_27.addWidget(self.TDRIVE)
        self.horizontalLayout_2.addLayout(self.verticalLayout_27)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_13.addWidget(self.label_13)
        self.DTIME = QtGui.QSpinBox(self.centralwidget)
        self.DTIME.setMaximum(7)
        self.DTIME.setObjectName(_fromUtf8("DTIME"))
        self.verticalLayout_13.addWidget(self.DTIME)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName(_fromUtf8("verticalLayout_37"))
        self.label_37 = QtGui.QLabel(self.centralwidget)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_37.addWidget(self.label_37)
        self.IDRIVE = QtGui.QSpinBox(self.centralwidget)
        self.IDRIVE.setMaximum(7)
        self.IDRIVE.setObjectName(_fromUtf8("IDRIVE"))
        self.verticalLayout_37.addWidget(self.IDRIVE)
        self.horizontalLayout_2.addLayout(self.verticalLayout_37)
        self.verticalLayout_49.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_46 = QtGui.QVBoxLayout()
        self.verticalLayout_46.setObjectName(_fromUtf8("verticalLayout_46"))
        self.label_46 = QtGui.QLabel(self.centralwidget)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_46.addWidget(self.label_46)
        self.INTCLK = QtGui.QSpinBox(self.centralwidget)
        self.INTCLK.setMaximum(7)
        self.INTCLK.setObjectName(_fromUtf8("INTCLK"))
        self.verticalLayout_46.addWidget(self.INTCLK)
        self.gridLayout.addLayout(self.verticalLayout_46, 0, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_16.addWidget(self.label_16)
        self.SPDGAIN = QtGui.QSpinBox(self.centralwidget)
        self.SPDGAIN.setMaximum(4096)
        self.SPDGAIN.setObjectName(_fromUtf8("SPDGAIN"))
        self.verticalLayout_16.addWidget(self.SPDGAIN)
        self.gridLayout.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.verticalLayout_44 = QtGui.QVBoxLayout()
        self.verticalLayout_44.setObjectName(_fromUtf8("verticalLayout_44"))
        self.label_44 = QtGui.QLabel(self.centralwidget)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_44.addWidget(self.label_44)
        self.HALLPOL = QtGui.QSpinBox(self.centralwidget)
        self.HALLPOL.setMaximum(1)
        self.HALLPOL.setObjectName(_fromUtf8("HALLPOL"))
        self.verticalLayout_44.addWidget(self.HALLPOL)
        self.gridLayout.addLayout(self.verticalLayout_44, 1, 0, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_15.addWidget(self.label_15)
        self.BYPFILT = QtGui.QSpinBox(self.centralwidget)
        self.BYPFILT.setMaximum(1)
        self.BYPFILT.setObjectName(_fromUtf8("BYPFILT"))
        self.verticalLayout_15.addWidget(self.BYPFILT)
        self.gridLayout.addLayout(self.verticalLayout_15, 1, 1, 1, 1)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_18.addWidget(self.label_18)
        self.FILK1 = QtGui.QSpinBox(self.centralwidget)
        self.FILK1.setMaximum(4096)
        self.FILK1.setObjectName(_fromUtf8("FILK1"))
        self.verticalLayout_18.addWidget(self.FILK1)
        self.gridLayout.addLayout(self.verticalLayout_18, 1, 2, 1, 1)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_28.addWidget(self.label_28)
        self.FILK2 = QtGui.QSpinBox(self.centralwidget)
        self.FILK2.setMaximum(4096)
        self.FILK2.setObjectName(_fromUtf8("FILK2"))
        self.verticalLayout_28.addWidget(self.FILK2)
        self.gridLayout.addLayout(self.verticalLayout_28, 2, 0, 1, 1)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_17.addWidget(self.label_17)
        self.BYPCOMP = QtGui.QSpinBox(self.centralwidget)
        self.BYPCOMP.setMaximum(1)
        self.BYPCOMP.setObjectName(_fromUtf8("BYPCOMP"))
        self.verticalLayout_17.addWidget(self.BYPCOMP)
        self.gridLayout.addLayout(self.verticalLayout_17, 3, 0, 1, 1)
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.COMK1 = QtGui.QSpinBox(self.centralwidget)
        self.COMK1.setMaximum(4096)
        self.COMK1.setObjectName(_fromUtf8("COMK1"))
        self.verticalLayout_19.addWidget(self.COMK1)
        self.gridLayout.addLayout(self.verticalLayout_19, 3, 1, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_14.addWidget(self.label_14)
        self.AA_SETPT = QtGui.QSpinBox(self.centralwidget)
        self.AA_SETPT.setMaximum(15)
        self.AA_SETPT.setObjectName(_fromUtf8("AA_SETPT"))
        self.verticalLayout_14.addWidget(self.AA_SETPT)
        self.gridLayout.addLayout(self.verticalLayout_14, 4, 0, 1, 1)
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.label_29 = QtGui.QLabel(self.centralwidget)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_29.addWidget(self.label_29)
        self.COMK2 = QtGui.QSpinBox(self.centralwidget)
        self.COMK2.setMaximum(4096)
        self.COMK2.setObjectName(_fromUtf8("COMK2"))
        self.verticalLayout_29.addWidget(self.COMK2)
        self.gridLayout.addLayout(self.verticalLayout_29, 4, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.logbox = QtGui.QTextEdit(self.centralwidget)
        self.logbox.setObjectName(_fromUtf8("logbox"))
        self.horizontalLayout_5.addWidget(self.logbox)
        self.verticalLayout_49.addLayout(self.horizontalLayout_5)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_12.addWidget(self.label_12)
        self.OCPDEG = QtGui.QSpinBox(self.centralwidget)
        self.OCPDEG.setMaximum(3)
        self.OCPDEG.setObjectName(_fromUtf8("OCPDEG"))
        self.verticalLayout_12.addWidget(self.OCPDEG)
        self.gridLayout_2.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.OCPTH = QtGui.QSpinBox(self.centralwidget)
        self.OCPTH.setMaximum(3)
        self.OCPTH.setObjectName(_fromUtf8("OCPTH"))
        self.verticalLayout_10.addWidget(self.OCPTH)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 0, 1, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.OVTH = QtGui.QSpinBox(self.centralwidget)
        self.OVTH.setMaximum(1)
        self.OVTH.setObjectName(_fromUtf8("OVTH"))
        self.verticalLayout_9.addWidget(self.OVTH)
        self.gridLayout_2.addLayout(self.verticalLayout_9, 0, 2, 1, 1)
        self.verticalLayout_30 = QtGui.QVBoxLayout()
        self.verticalLayout_30.setObjectName(_fromUtf8("verticalLayout_30"))
        self.label_30 = QtGui.QLabel(self.centralwidget)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_30.addWidget(self.label_30)
        self.VREG_EN = QtGui.QSpinBox(self.centralwidget)
        self.VREG_EN.setMaximum(1)
        self.VREG_EN.setObjectName(_fromUtf8("VREG_EN"))
        self.verticalLayout_30.addWidget(self.VREG_EN)
        self.gridLayout_2.addLayout(self.verticalLayout_30, 0, 3, 1, 1)
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName(_fromUtf8("verticalLayout_39"))
        self.label_39 = QtGui.QLabel(self.centralwidget)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_39.addWidget(self.label_39)
        self.LOOPGAIN = QtGui.QSpinBox(self.centralwidget)
        self.LOOPGAIN.setMaximum(1024)
        self.LOOPGAIN.setObjectName(_fromUtf8("LOOPGAIN"))
        self.verticalLayout_39.addWidget(self.LOOPGAIN)
        self.gridLayout_2.addLayout(self.verticalLayout_39, 0, 4, 1, 1)
        self.verticalLayout_38 = QtGui.QVBoxLayout()
        self.verticalLayout_38.setObjectName(_fromUtf8("verticalLayout_38"))
        self.label_38 = QtGui.QLabel(self.centralwidget)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_38.addWidget(self.label_38)
        self.SPED = QtGui.QSpinBox(self.centralwidget)
        self.SPED.setMaximum(4096)
        self.SPED.setObjectName(_fromUtf8("SPED"))
        self.verticalLayout_38.addWidget(self.SPED)
        self.gridLayout_2.addLayout(self.verticalLayout_38, 1, 0, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.RLOCK = QtGui.QSpinBox(self.centralwidget)
        self.RLOCK.setMaximum(1)
        self.RLOCK.setObjectName(_fromUtf8("RLOCK"))
        self.verticalLayout_6.addWidget(self.RLOCK)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 2, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_7.addWidget(self.label_7)
        self.VMOV = QtGui.QSpinBox(self.centralwidget)
        self.VMOV.setMaximum(1)
        self.VMOV.setObjectName(_fromUtf8("VMOV"))
        self.verticalLayout_7.addWidget(self.VMOV)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 1, 1, 1)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_20.addWidget(self.label_20)
        self.CPFAIL = QtGui.QSpinBox(self.centralwidget)
        self.CPFAIL.setMaximum(1)
        self.CPFAIL.setObjectName(_fromUtf8("CPFAIL"))
        self.verticalLayout_20.addWidget(self.CPFAIL)
        self.gridLayout_2.addLayout(self.verticalLayout_20, 2, 2, 1, 1)
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName(_fromUtf8("verticalLayout_31"))
        self.label_31 = QtGui.QLabel(self.centralwidget)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_31.addWidget(self.label_31)
        self.UVLO = QtGui.QSpinBox(self.centralwidget)
        self.UVLO.setMaximum(1)
        self.UVLO.setObjectName(_fromUtf8("UVLO"))
        self.verticalLayout_31.addWidget(self.UVLO)
        self.gridLayout_2.addLayout(self.verticalLayout_31, 2, 3, 1, 1)
        self.verticalLayout_40 = QtGui.QVBoxLayout()
        self.verticalLayout_40.setObjectName(_fromUtf8("verticalLayout_40"))
        self.label_40 = QtGui.QLabel(self.centralwidget)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_40.addWidget(self.label_40)
        self.OTS = QtGui.QSpinBox(self.centralwidget)
        self.OTS.setMaximum(1)
        self.OTS.setObjectName(_fromUtf8("OTS"))
        self.verticalLayout_40.addWidget(self.OTS)
        self.gridLayout_2.addLayout(self.verticalLayout_40, 2, 4, 1, 1)
        self.verticalLayout_42 = QtGui.QVBoxLayout()
        self.verticalLayout_42.setObjectName(_fromUtf8("verticalLayout_42"))
        self.label_42 = QtGui.QLabel(self.centralwidget)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_42.addWidget(self.label_42)
        self.CPOC = QtGui.QSpinBox(self.centralwidget)
        self.CPOC.setMaximum(1)
        self.CPOC.setObjectName(_fromUtf8("CPOC"))
        self.verticalLayout_42.addWidget(self.CPOC)
        self.gridLayout_2.addLayout(self.verticalLayout_42, 2, 5, 1, 1)
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName(_fromUtf8("verticalLayout_41"))
        self.label_41 = QtGui.QLabel(self.centralwidget)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_41.addWidget(self.label_41)
        self.OCP = QtGui.QSpinBox(self.centralwidget)
        self.OCP.setMaximum(1)
        self.OCP.setObjectName(_fromUtf8("OCP"))
        self.verticalLayout_41.addWidget(self.OCP)
        self.gridLayout_2.addLayout(self.verticalLayout_41, 2, 6, 1, 1)
        self.verticalLayout_51 = QtGui.QVBoxLayout()
        self.verticalLayout_51.setObjectName(_fromUtf8("verticalLayout_51"))
        self.ENABLE = QtGui.QPushButton(self.centralwidget)
        self.ENABLE.setObjectName(_fromUtf8("ENABLE"))
        self.verticalLayout_51.addWidget(self.ENABLE)
        self.DISABLE = QtGui.QPushButton(self.centralwidget)
        self.DISABLE.setObjectName(_fromUtf8("DISABLE"))
        self.verticalLayout_51.addWidget(self.DISABLE)
        self.gridLayout_2.addLayout(self.verticalLayout_51, 0, 6, 1, 1)
        self.RESET = QtGui.QPushButton(self.centralwidget)
        self.RESET.setObjectName(_fromUtf8("RESET"))
        self.gridLayout_2.addWidget(self.RESET, 1, 6, 1, 1)
        self.fault = QtGui.QPushButton(self.centralwidget)
        self.fault.setObjectName(_fromUtf8("fault"))
        self.gridLayout_2.addWidget(self.fault, 1, 5, 1, 1)
        self.verticalLayout_49.addLayout(self.gridLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_49, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.speedSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speedValue.setValue)
        QtCore.QObject.connect(self.speedValue, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.speedSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.AG_SETPT, self.ENPOL)
        MainWindow.setTabOrder(self.ENPOL, self.DIRPOL)
        MainWindow.setTabOrder(self.DIRPOL, self.BRKPOL)
        MainWindow.setTabOrder(self.BRKPOL, self.SYNRECT)
        MainWindow.setTabOrder(self.SYNRECT, self.PWMF)
        MainWindow.setTabOrder(self.PWMF, self.SPDMODE)
        MainWindow.setTabOrder(self.SPDMODE, self.FGSEL)
        MainWindow.setTabOrder(self.FGSEL, self.BRKMOD)
        MainWindow.setTabOrder(self.BRKMOD, self.RETRY)
        MainWindow.setTabOrder(self.RETRY, self.ADVANCE)
        MainWindow.setTabOrder(self.ADVANCE, self.SPDREVS)
        MainWindow.setTabOrder(self.SPDREVS, self.MINSPD)
        MainWindow.setTabOrder(self.MINSPD, self.BASIC)
        MainWindow.setTabOrder(self.BASIC, self.SPEDTH)
        MainWindow.setTabOrder(self.SPEDTH, self.MOD120)
        MainWindow.setTabOrder(self.MOD120, self.LRTIME)
        MainWindow.setTabOrder(self.LRTIME, self.HALLRST)
        MainWindow.setTabOrder(self.HALLRST, self.DELAY)
        MainWindow.setTabOrder(self.DELAY, self.AUTOADV)
        MainWindow.setTabOrder(self.AUTOADV, self.AUTOGAIN)
        MainWindow.setTabOrder(self.AUTOGAIN, self.ENSINE)
        MainWindow.setTabOrder(self.ENSINE, self.TDRIVE)
        MainWindow.setTabOrder(self.TDRIVE, self.DTIME)
        MainWindow.setTabOrder(self.DTIME, self.IDRIVE)
        MainWindow.setTabOrder(self.IDRIVE, self.INTCLK)
        MainWindow.setTabOrder(self.INTCLK, self.SPDGAIN)
        MainWindow.setTabOrder(self.SPDGAIN, self.HALLPOL)
        MainWindow.setTabOrder(self.HALLPOL, self.BYPFILT)
        MainWindow.setTabOrder(self.BYPFILT, self.FILK1)
        MainWindow.setTabOrder(self.FILK1, self.FILK2)
        MainWindow.setTabOrder(self.FILK2, self.BYPCOMP)
        MainWindow.setTabOrder(self.BYPCOMP, self.COMK1)
        MainWindow.setTabOrder(self.COMK1, self.AA_SETPT)
        MainWindow.setTabOrder(self.AA_SETPT, self.COMK2)
        MainWindow.setTabOrder(self.COMK2, self.OCPDEG)
        MainWindow.setTabOrder(self.OCPDEG, self.OCPTH)
        MainWindow.setTabOrder(self.OCPTH, self.OVTH)
        MainWindow.setTabOrder(self.OVTH, self.VREG_EN)
        MainWindow.setTabOrder(self.VREG_EN, self.LOOPGAIN)
        MainWindow.setTabOrder(self.LOOPGAIN, self.SPED)
        MainWindow.setTabOrder(self.SPED, self.RLOCK)
        MainWindow.setTabOrder(self.RLOCK, self.VMOV)
        MainWindow.setTabOrder(self.VMOV, self.CPFAIL)
        MainWindow.setTabOrder(self.CPFAIL, self.UVLO)
        MainWindow.setTabOrder(self.UVLO, self.OTS)
        MainWindow.setTabOrder(self.OTS, self.CPOC)
        MainWindow.setTabOrder(self.CPOC, self.OCP)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "AG_SETPT", None))
        self.label_45.setText(_translate("MainWindow", "ENPOL", None))
        self.label_4.setText(_translate("MainWindow", "DIRPOL", None))
        self.label_43.setText(_translate("MainWindow", "BRKPOL", None))
        self.label_8.setText(_translate("MainWindow", "SYNRECT", None))
        self.label_32.setText(_translate("MainWindow", "PWMF", None))
        self.label_2.setText(_translate("MainWindow", "SPDMODE", None))
        self.label_3.setText(_translate("MainWindow", "FGSEL", None))
        self.label_21.setText(_translate("MainWindow", "BRKMOD", None))
        self.label_22.setText(_translate("MainWindow", "RETRY", None))
        self.label_48.setText(_translate("MainWindow", "SPDREVS", None))
        self.label_23.setText(_translate("MainWindow", "MINSPD", None))
        self.label_33.setText(_translate("MainWindow", "ADVANCE", None))
        self.label_34.setText(_translate("MainWindow", "BASIC", None))
        self.label_25.setText(_translate("MainWindow", "SPEDTH", None))
        self.label_24.setText(_translate("MainWindow", "MOD120", None))
        self.label_47.setText(_translate("MainWindow", "LRTIME", None))
        self.label_5.setText(_translate("MainWindow", "HALLRST", None))
        self.label_11.setText(_translate("MainWindow", "DELAY", None))
        self.label_26.setText(_translate("MainWindow", "AUTOADV", None))
        self.label_35.setText(_translate("MainWindow", "AUTOGAIN", None))
        self.label_36.setText(_translate("MainWindow", "ENSINE", None))
        self.label_27.setText(_translate("MainWindow", "TDRIVE", None))
        self.label_13.setText(_translate("MainWindow", "DTIME", None))
        self.label_37.setText(_translate("MainWindow", "IDRIVE", None))
        self.label_46.setText(_translate("MainWindow", "INTCLK", None))
        self.label_16.setText(_translate("MainWindow", "SPDGAIN", None))
        self.label_44.setText(_translate("MainWindow", "HALLPOL", None))
        self.label_15.setText(_translate("MainWindow", "BYPFILT", None))
        self.label_18.setText(_translate("MainWindow", "FILK1", None))
        self.label_28.setText(_translate("MainWindow", "FILK2", None))
        self.label_17.setText(_translate("MainWindow", "BYPCOMP", None))
        self.label_19.setText(_translate("MainWindow", "COMK1", None))
        self.label_14.setText(_translate("MainWindow", "AA_SETPT", None))
        self.label_29.setText(_translate("MainWindow", "COMK2", None))
        self.label_12.setText(_translate("MainWindow", "OCPDEG", None))
        self.label_10.setText(_translate("MainWindow", "OCPTH", None))
        self.label_9.setText(_translate("MainWindow", "OVTH", None))
        self.label_30.setText(_translate("MainWindow", "VREG_EN", None))
        self.label_39.setText(_translate("MainWindow", "LOOPGAIN", None))
        self.label_38.setText(_translate("MainWindow", "SPED", None))
        self.label_6.setText(_translate("MainWindow", "RLOCK", None))
        self.label_7.setText(_translate("MainWindow", "VMOV", None))
        self.label_20.setText(_translate("MainWindow", "CPFAIL", None))
        self.label_31.setText(_translate("MainWindow", "UVLO", None))
        self.label_40.setText(_translate("MainWindow", "OTS", None))
        self.label_42.setText(_translate("MainWindow", "CPOC", None))
        self.label_41.setText(_translate("MainWindow", "OCP", None))
        self.ENABLE.setText(_translate("MainWindow", "Enable", None))
        self.DISABLE.setText(_translate("MainWindow", "Disable", None))
        self.RESET.setText(_translate("MainWindow", "Reset", None))
        self.fault.setText(_translate("MainWindow", "Read Fault", None))

