# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/mainWindow.ui'
#
# Created: Sun Nov 23 10:53:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(777, 555)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_6 = QtGui.QFrame(self.centralwidget)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_8 = QtGui.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.comboBox_5 = QtGui.QComboBox(self.frame_8)
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.verticalLayout_3.addWidget(self.comboBox_5)
        self.comboBox_7 = QtGui.QComboBox(self.frame_8)
        self.comboBox_7.setObjectName(_fromUtf8("comboBox_7"))
        self.verticalLayout_3.addWidget(self.comboBox_7)
        self.gridLayout_2.addWidget(self.frame_8, 3, 2, 1, 1)
        self.frame_9 = QtGui.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_9)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.frame_9)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.gridLayout_2.addWidget(self.frame_9, 3, 3, 1, 1)
        self.frame_3 = QtGui.QFrame(self.frame_6)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.comboBox_3 = QtGui.QComboBox(self.frame_3)
        self.comboBox_3.setGeometry(QtCore.QRect(0, 0, 70, 27))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.comboBox_3.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(90, 0, 81, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.frame_3, 1, 4, 1, 2)
        self.Minimap = QtGui.QFrame(self.frame_6)
        self.Minimap.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Minimap.setFrameShadow(QtGui.QFrame.Raised)
        self.Minimap.setObjectName(_fromUtf8("Minimap"))
        self.label_6 = QtGui.QLabel(self.Minimap)
        self.label_6.setGeometry(QtCore.QRect(90, 0, 63, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.Minimap, 2, 0, 2, 2)
        self.frame_5 = QtGui.QFrame(self.frame_6)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.comboBox_4 = QtGui.QComboBox(self.frame_5)
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.verticalLayout.addWidget(self.comboBox_4)
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_6 = QtGui.QComboBox(self.frame_5)
        self.comboBox_6.setObjectName(_fromUtf8("comboBox_6"))
        self.verticalLayout.addWidget(self.comboBox_6)
        self.gridLayout_2.addWidget(self.frame_5, 2, 2, 1, 1)
        self.frame_7 = QtGui.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_7)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton = QtGui.QPushButton(self.frame_7)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtGui.QPushButton(self.frame_7)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.frame_7)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_2.addWidget(self.frame_7, 2, 3, 1, 1)
        self.frame_10 = QtGui.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.label_7 = QtGui.QLabel(self.frame_10)
        self.label_7.setGeometry(QtCore.QRect(60, 0, 123, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.frame_10, 2, 4, 2, 2)
        self.frame = QtGui.QFrame(self.frame_6)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(0, 0, 70, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(210, 0, 87, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.frame, 0, 0, 2, 4)
        self.frame_2 = QtGui.QFrame(self.frame_6)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.comboBox_2 = QtGui.QComboBox(self.frame_2)
        self.comboBox_2.setGeometry(QtCore.QRect(0, 0, 70, 27))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(90, 0, 81, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.frame_2, 0, 4, 1, 2)
        self.gridLayout.addWidget(self.frame_6, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuWindow = QtGui.QMenu(self.menubar)
        self.menuWindow.setObjectName(_fromUtf8("menuWindow"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton", None))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "feed 1", None))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "feed 2", None))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "feed n", None))
        self.label_5.setText(_translate("MainWindow", "side camera", None))
        self.label_6.setText(_translate("MainWindow", "mini map", None))
        self.label.setText(_translate("MainWindow", "Hand type", None))
        self.label_2.setText(_translate("MainWindow", "Arm mode", None))
        self.pushButton_4.setText(_translate("MainWindow", "function 1", None))
        self.pushButton.setText(_translate("MainWindow", "function 2", None))
        self.pushButton_2.setText(_translate("MainWindow", "function 3", None))
        self.pushButton_3.setText(_translate("MainWindow", "function 4", None))
        self.label_7.setText(_translate("MainWindow", "display other data", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "feed 1", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "feed 2", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "feed n", None))
        self.label_3.setText(_translate("MainWindow", "Main camera", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "feed 1", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "feed 2", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "feed n", None))
        self.label_4.setText(_translate("MainWindow", "side camera", None))
        self.menuWindow.setTitle(_translate("MainWindow", "window", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))

